version: '2'
services:
  postgres:
    container_name: postgres
    ports:
      - 5432:5432/tcp
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: danachury
      POSTGRES_PASSWORD: danachury12345
      POSTGRES_DB: chtauth
#    networks:
#      - bridge
    volumes:
      - ${PWD}/scripts:/scripts
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U danachury"]
#      interval: 30s
#      timeout: 30s
#      retries: 3
